name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checout@v5
    - name: Setup Go
      uses: actions/checout@v5
      with:
        go-version: '1.21.x'
    - name: Build
      run: go build -v ./backend/...
    - name: Test
      run: go test -v ./backend/...